name: publish-github-apps-test

on:
  workflow_dispatch:
    # types:
    #   - publish-github-app

jobs:
  publish-github-app: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: Repository Dispatch
      uses: OSX-RSPlug-a/github_actions_pract06@latest
      with:
        token: ${{ secrets.TOK }}
        repository: OSX-RSPlug-a/github_actions_pract06/
        event-type: publish-github-app